### ISSUE TITLE
Send same data source to two measure routes

### ISSUE THREAD

**Issue by mcongrove** [dmolin/flightSimPanels#3]
Looking through the code, I'm not seeing a way to send the same data source to two different routes. For instance, the `attitude.roll` is used by the Attitude Indicator as well as the Turn-and-Slip Indicator.

Am I missing something, or is this not supported because of the `measure.xtype` handler registration?

**Comment by dmolin** [comment]
Hi Matthew, I'll have a look later but If I understand correctly your question, you can't 'reuse' a data source for 2 different indicators. Each data block comes down from X-Plane and is mapped to a Measure (I'm going by memory now, so apologies if I'm being a bit vague..). 
Essentially, X-Plane sends the data related to each instrument (the x-type is the mapping that allows the Node.js server to identify who-is-who and map each area of the binary packet into the corresponding "measure"). 
So, if the turn-and-slip instrument data returned by X-Plane has a 'roll' information, it will be in the relevant data block received via UDP by the Node.js server and it will be passed down to the turn-and-slip Javascript Measure (yet to be created).
So, you don't "reuse" measures across instruments. X-Plane sends each instrument values in contiguous data blocks in the UDP packet; we 'unpack' them and create one "measure" for each one of them (and then transfer the list of all the json measures to the connected clients via Socket.io... and the client decodes them using the client side code associated with each measure..)

**Comment by mcongrove** [comment]
From what I'm seeing, it doesn't look like the turn-and-slip information (xtype 18) has a roll value. I'm seeing the following data:

#### xtype 18 (AOA, side-slip, paths)
|key|value|type|
|---|---|---|
|alpha|6.043|deg|
|beta|0.128|deg|
|hpath|22.72|deg|
|vpath|7.783|deg|
|slip|0.020|deg|

#### xtype 17 (pitch, roll, headings)
|key|value|type|
|---|---|---|
|pitch|14.00|deg|
|roll|-7.510|deg|
|hding|22.03|true|
|hding|27.22|mag|

**Comment by dmolin** [comment]
..if you don't see it, then it's not there :)
I just assumed that it was present because of your sentence "the attitude.roll is used by the Attitude Indicator as well as the Turn-and-Slip Indicator"...
Point is, X-Plane provides you with all the information necessary for each instrument (I'd be concerned if otherwise); the time-wasting part of this reverse engineering game is to understand what each "key" means... and this is a game of trials and errors :)

**Comment by mcongrove** [comment]
Hmm, alright. I'll keep playing with it and trying to decode what the alpha/beta/hpath/vpath values are, exactly, and see if they somehow align with the roll.

Thanks!

(PS - Should have the T&S ready for a PR when I do)

**Comment by dmolin** [comment]
Cool Matthew. keep me in the know :)

**Comment by mcongrove** [comment]
Still can't figure it out; I've appealed to others to assist with the math :)

Here's what I have so far: https://github.com/mcongrove/flightSimPanels/commit/47b0ba12dcc43826b734c99674a9e56ed865a958

Still can't figure out the relationship between alpha, beta, hpath, vpath, and the rate of turn. [This](http://www.xsquawkbox.net/xpsdk/mediawiki/sim%252Fflightmodel%252Fmisc%252Fturnrate_roll) and [this](https://www.ideals.illinois.edu/bitstream/handle/2142/44145/Steven_Pelech.pdf?sequence=1) didn't really help much, but maybe it'll click for you?

**Comment by mcongrove** [comment]
Regarding the original reason for this ticket, it's definitely needed. For instance, the Attitude Indicator uses `xtype` 17 for pitch and roll information. However, the Heading Indicator also needs `xtype` 17, as it contains the magnetic and true headings. There's a couple other instances where the `xtype` data would be necessary for two instruments.

Also worth noting that some instruments might require __two__ `xtypes`. Examples would be the temperature and TAS in the Airspeed Indicator and air pressure in the Altitude Indicator.

Obviously I just started looking at this code, so I haven't really dug too much into the architecture... but if you have any ideas for implementations for the two issues above I can try and work on it.

**Comment by dmolin** [comment]
Mmmhh... that sucks, since my assumption was that each dataref block was
modeling one instrument, and that doesn't seem to be the case then...
Ok, I think I've an idea on a possible solution.. in my mind, no matter
what happens in x-plane, the node server sends down measures, where each
measure corresponds to one instrument, with all the info that the
instrument requires to properly function..
My idea is to radically change the way the payload gets translated into
measures (the Measure factory) and declaring each measure as identified by
one or more xtypes.. today I'll spend some time on it.. I think it could
work :)

**Comment by dmolin** [comment]
Ok, I got an idea while I was at the gym this morning; I ran it in my mind
and it seems to be good enough to be worth a try; This afternoon (it's 1pm
now) I'll give it a go; I'll change drastically the way Measures are
registered and the way the MeasureFactory works (introducing also a
decoding table for the x-types). Let's see if it works :)

send replies to:
Davide Alberto Molin
davide.molin@gmail.com

find me on:
LinkedIn: http://www.linkedin.com/in/davidemolin
My Homepage: http://www.davidemolin.com
My Online Courses: http://fedtraining.usefedora.com
My GitHub: http://github.com/dmolin
My Blog: http://developme.wordpress.com
My Tweets: http://www.twitter.com/davidemolin
My Vimeo: http://vimeo.com/davidemolin

**Comment by mcongrove** [comment]
Thanks for working on this so fast :) After you've got the re-factor done I'll update my code and submit PRs. I've added landing gear, flaps, turn-and-slip, and the heading indicators:

![flightSimPanels](https://camo.githubusercontent.com/c5358a88647963153845d4b06b3d8bc09adec583/68747470733a2f2f7261772e6769746875622e636f6d2f6d636f6e67726f76652f666c6967687453696d50616e656c732f6d61737465722f6173736574732f666c6967687473696d70616e656c732e706e67)

I also updated all the instrument designs so they're more uniform, completely layered, and don't include things that aren't implemented (e.g. air temp in the airspeed indicator). If you want those, let me know and I'll also include them in a PR.

**Comment by dmolin** [comment]
Wow that's cool. really beautiful work mate!

You can bet I want those :D

I've almost done with the refactor. Now the new factory is complete and
I've already converted the speed and enginerpm indicators;

Now I need to go to a party (damn social activities.. LOL)
When I come back I think I should be able to finish and commit.
Expect a few changes:
Under the "services" folder you'll have now:
  datarefs/
      3/
     18/
     37/

  measures/
     speed/
     enginerpm/


datarefs/ is a folder containing a commonjs module for each xtype sent out
by the simulator
measures/ contains the code to build each Measure object sent to the client
(and the usual clientside code)

Basically, the index.js that you have now under each measure is going to be
moved under the datarefs/ folder, because over there is the logic to
translate a UDP packet into the correspondig json model.
The "measures/xxx" module instead will just assemble the measure object
having access to all the datarefs decoded from the message sent by the
server; this way each measure(instrument panel) can be obtained composing
any (or all) of the datarefs available..


Best
Davide


send replies to:
Davide Alberto Molin
davide.molin@gmail.com

find me on:
LinkedIn: http://www.linkedin.com/in/davidemolin
My Homepage: http://www.davidemolin.com
My Online Courses: http://fedtraining.usefedora.com
My GitHub: http://github.com/dmolin
My Blog: http://developme.wordpress.com
My Tweets: http://www.twitter.com/davidemolin
My Vimeo: http://vimeo.com/davidemolin

**Comment by dmolin** [comment]
Ok, work done :)

This is what is changed:
Now we have 2 set of decoders/mappers:

- dataref processors:
   functions responsible for transforming the binary representation of a
X-Plane dataref type into a human readable JSON object (this is the work
that I was previously doing in each measure module index.js..)

- measure processors
   functions responsible for returning the complete JSON representation of
an instrument. it can be corresponding to one of the dataref JSON object
(in that case the measure processor acts simply as a proxy to a dataref
processor decoded object) or a complex object assembled using multiple
dataref decoded objects...

You can also see that now under the "services/" folder we have 2
sub-folders:
- datarefs/
     contains a list of commonjs modules, one for each xtype that we want
to be able to decode.
     each module's index.js is just a decoding function (the dataref
processor function) that return the JSON representation of the binary
payload for that xtype

- measures/
     contains a list of commonjs modules, one for each instrument. The
index.js is the "processor" function responsible for returning the JSON
object representing that instrument. most of the time the function can act
simply as a proxy and return the same exact JSON object decoded by the
dataref processor; other times (like for the turn coordinator, I guess, it
can return a complex object resulting from the composition of multiple
dataref decoded objects..). Each measure processor function received in
input a configuration object containing the hashtable with the decoded
xtypes and a Helper function.

This should give us the maximum flexibility in assembling each instrument
with as many xtype we need.

Best
Davide


send replies to:
Davide Alberto Molin
davide.molin@gmail.com

find me on:
LinkedIn: http://www.linkedin.com/in/davidemolin
My Homepage: http://www.davidemolin.com
My Online Courses: http://fedtraining.usefedora.com
My GitHub: http://github.com/dmolin
My Blog: http://developme.wordpress.com
My Tweets: http://www.twitter.com/davidemolin
My Vimeo: http://vimeo.com/davidemolin

**Comment by mcongrove** [comment]
This looks awesome Davide! I'll work on getting this sync'd with all my stuff; when I do I'll send you a link to my latest so you can test, and if it's acceptable, I'll submit it as a PR. Thanks again for handling this all so quickly.

**Comment by mcongrove** [comment]
New art assets and new dials (DG, flaps, gear, turn coordinator) are pushed to `master` here: https://github.com/mcongrove/flightSimPanels

Give it a go, see if you approve.

I still have some work to do; need to update the value-to-angle definitions for some of the gauges, but they should be fairly close (I mimicked the dials you had as closely as possible, so they should align almost perfectly).

**Comment by mcongrove** [comment]
Alright, I finished updating the angle interpolations. I needed to add some additional logic (e.g. min, max) and also wanted to abstract the logic out of the `update` method so it didn't run constantly.

You can see the changes in this commit: https://github.com/mcongrove/flightSimPanels/commit/5813e612776706f383e1de287dd7fb8e18b0efcf

I still can't get the Turn-and-Slip Indicator working; there's no simple access to the data (like the `sim/flightmodel/misc/turnrate_roll` dataref), and I don't know the math well enough to get it from the data that is available :-\

**Comment by dmolin** [comment]
Cool Matthew :). good thing a setup() function too.

One thing though: there's no reason in checking for the existence/type of
the setup/render/update functions in the widget. They are actually
functions defined in the Widget object itself (you can see them defined as
no-op functions in the widget class), so no necessity for any check, since
their existence and type is guaranteed (a setup() no-op should be added at
the widget class too)... I tend to like this approach, since it simplifies
the code a bit and makes it more terse too.

The turn-and-slip seems to be really a bad boy... :(

send replies to:
Davide Alberto Molin
davide.molin@gmail.com

find me on:
LinkedIn: http://www.linkedin.com/in/davidemolin
My Homepage: http://www.davidemolin.com
My Online Courses: http://fedtraining.usefedora.com
My GitHub: http://github.com/dmolin
My Blog: http://developme.wordpress.com
My Tweets: http://www.twitter.com/davidemolin
My Vimeo: http://vimeo.com/davidemolin

On Mon, Jan 19, 2015 at 12:31 AM, Matthew Congrove <notifications@github.com

**Comment by mcongrove** [comment]
Ah, I didn't see that. I just knew it was failing for `setup` when I initially added it and got copy+paste happy. Revised!

I've also added an inop marker to the turn-and-slip until I can figure it out. That way people can still run the project and play around without thinking it's messed up.

**Comment by pedroponte** [comment]
Hi guys, I just want to congratulate you both for the excellent work you're doing and to say I'm looking forward to use your instrument panel :+1:  :)
